export const LOADING = 'LOADING_ACTION';
export const ERROR = 'FAILURE';

export const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
export const ADDING_BRANCHE = 'ADDING_BRANCHE';
export const ADD_BRANCHE_SUCCESS = 'ADD_BRANCHE_SUCCESS';
export const REMOVE_BRANCHE_SUCCESS = 'REMOVE_BRANCHE_SUCCESS';

export const GET_WORKERS_SUCCESS = 'GET_WORKERS_SUCCESS';
export const ADDING_WORKER = 'ADDING_WORKER';
export const ADD_WORKERS_SUCCESS = 'ADD_WORKERS_SUCCESS';
