export const LOADING = 'LOADING_ACTION';
export const ERROR = 'FAILURE';

export const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
export const ADDING_BRANCHE = 'ADDING_BRANCHE';
export const ADD_BRANCHE_SUCCESS = 'ADD_BRANCHE_SUCCESS';
export const REMOVE_BRANCHE_SUCCESS = 'REMOVE_BRANCHE_SUCCESS';
export const GET_BRANCH_WORKER_SUCCESS = 'GET_BRANCH_WORKER_SUCCESS';
export const GET_BRANCH_IMPORTS_SUCCESS = 'GET_BRANCH_IMPORTS_SUCCESS';
export const GET_BRANCH_EXPORTS_SUCCESS = 'GET_BRANCH_EXPORTS_SUCCESS';
export const GET_BRANCH_PRODUCTS_SUCCESS = 'GET_BRANCH_PRODUCTS_SUCCESS';

export const GET_WORKERS_SUCCESS = 'GET_WORKERS_SUCCESS';
export const ADDING_WORKER = 'ADDING_WORKER';
export const ADD_WORKERS_SUCCESS = 'ADD_WORKERS_SUCCESS';
export const REMOVING_WORKER = 'REMOVING_WORKER';
export const REMOVE_WORKER_SUCCESS = 'REMOVE_WORKER_SUCCESS';

export const ADDING_PROVIDER = 'ADDING_PROVIDER';
export const ADD_PROVIDER_SUCCESS = 'ADD_PROVIDER_SUCCESS';
export const GET_PROVIDERS_SUCCESS = 'GET_PROVIDERS_SUCCESS';
export const REMOVING_PROVIDER = 'REMOVING_PROVIDER';
export const REMOVE_PROVIDER_SUCCESS = 'REMOVE_PROVIDER_SUCCESS';

export const GET_USER_IMPORTS_SUCCESS = 'GET_USER_IMPORTS_SUCCESS';
export const GET_EXPORT_SUCCESS = 'GET_EXPORT_SUCCESS';
export const GET_INCOME_SUCCESS = 'GET_INCOME_SUCCESS';