
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const ERROR = 'FAILURE';

export const ADDING_PRODUCT = 'ADDING_PRODUCT';
export const ADD_USER_IMPORT_SUCCESS = 'ADD_USER_IMPORT_SUCCESS';
export const ADD_WORKER_IMPORT_SUCCESS = 'ADD_WORKER_IMPORT_SUCCESS';
export const ADDED_PRODUCT = 'ADDED_PRODUCT';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_COUNT_SUCCESS = 'GET_PRODUCTS_COUNT_SUCCESS';

